spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      completedproposal: proposta-concluida.ex
    queue:
      pendingproposal: proposta-pendente.ms-analise-credito